<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-06-23 15:50

from django.conf import settings
=======
# Generated by Django 4.0.5 on 2022-06-15 08:01

>>>>>>> 14ae95d... first commit
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 14ae95d... first commit
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='new/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 14ae95d... first commit
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
<<<<<<< HEAD
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
=======
            ],
        ),
        migrations.CreateModel(
            name='Answer',
>>>>>>> 14ae95d... first commit
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
<<<<<<< HEAD
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.question'),
        ),
=======
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.question')),
            ],
        ),
>>>>>>> 14ae95d... first commit
    ]
