# Generated by Django 3.2.13 on 2022-06-29 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='articles/question/')),
                ('count', models.PositiveIntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('selected_question', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('create_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/answer/')),
                ('select', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.question')),
            ],
        ),
    ]
