# Generated by Django 3.2.13 on 2022-06-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/answer/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='articles/question/'),
        ),
    ]
