# Generated by Django 4.0.5 on 2022-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_question_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
