# Generated by Django 3.2.13 on 2022-06-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220624_0331'),
        ('articles', '0006_question_imgfile'),
    ]

    operations = [
    ]
