# Generated by Django 3.2.13 on 2022-06-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_merge_0003_auto_20220624_0331_0006_question_imgfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
