# Generated by Django 4.0.5 on 2022-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
