# Generated by Django 3.2.13 on 2022-06-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='selected_question',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
