# Generated by Django 4.0.5 on 2022-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_question_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_question',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
