# Generated by Django 4.0.5 on 2022-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_question_selected_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
