# Generated by Django 4.0.5 on 2022-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(blank=True),
        ),
    ]
