# Generated by Django 4.0.5 on 2022-06-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_git_address_profile_nickname_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.TextField(blank=True, null=True),
        ),
    ]
